### ISSUE TITLE
Errors when running model/gen_model.sh 

### ISSUE THREAD

**Issue by jiaola** [timsbiomed/tccm-model#1]
This error occurs when running gen_model.sh. It appears for every gen- command. Only output of gen-markdown is listed here. 

Error: no such option: --no-mergeimports
Usage: gen-markdown [OPTIONS] YAMLFILE
Try 'gen-markdown --help' for help.

The biolinkml version is 1.5.4 which is the latest release.

**Comment by hsolbrig** [comment]
This is being co-developed with the issue_tccm branch of biolinkml.
